apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami-uat
spec:
  destination:
    namespace: stream-uat-whoami
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://github.com/gloppasglop/stream-whoami.git
    targetRevision: HEAD
  sources:
    - path: "uat"
      repoURL: https://github.com/gloppasglop/stream-whoami.git
  project: stream
