apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stream-uat-whoami

resources:
  - ../base/

patches:
  - path: namespace.yaml
  - path: ingress-whoami.yaml
  - path: deployment-whoami.yaml
